# Generated by Django 3.2.9 on 2022-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
