# Generated by Django 3.2.9 on 2022-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_favourite_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='add',
        ),
        migrations.AddField(
            model_name='favourite_items',
            name='add',
            field=models.BooleanField(default=False),
        ),
    ]
