# Generated by Django 3.2.9 on 2022-05-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20220503_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite_items',
            new_name='FavouriteItems',
        ),
    ]
