# Generated by Django 3.2.9 on 2022-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_favourite_items_favouriteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteitems',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
