# Generated by Django 3.2.9 on 2022-05-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_favouriteitems_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='song',
        ),
    ]
