# Generated by Django 3.2.9 on 2022-05-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_favourite_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteitems',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.song', unique=True),
        ),
    ]
