# Generated by Django 3.2.9 on 2022-05-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_favouriteitems_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteitems',
            name='song',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.song'),
        ),
    ]
