# Generated by Django 3.2.9 on 2022-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_favouriteitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
