# Generated by Django 3.2.9 on 2022-05-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_song_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteitems',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='favouriteitems',
            name='song',
        ),
        migrations.RemoveField(
            model_name='favouriteitems',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='FavouriteItems',
        ),
    ]
