# Generated by Django 3.2.9 on 2022-05-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.song'),
        ),
    ]
