# Generated by Django 3.2.9 on 2022-05-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_comment_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
