# Generated by Django 3.2.9 on 2022-05-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20220511_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='customer',
        ),
    ]
