# Generated by Django 3.2.9 on 2022-05-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_remove_comment_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
