# Generated by Django 3.2.9 on 2022-05-12 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0026_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gen', models.CharField(choices=[('0', '-'), ('1', 'Pop'), ('2', 'Hip-Hop'), ('3', 'Rock'), ('4', 'Jazz'), ('5', 'Indian'), ('6', 'Dance/Electronic'), ('7', 'Country'), ('8', 'Metal'), ('9', 'K-Pop'), ('10', 'Acoustic')], default=0, max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
